//! Graph node types for representing build dependencies

use std::path::PathBuf;

use crate::{ActionId, Label};

/// Unique identifier for graph nodes
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NodeId(pub usize);

impl NodeId {
    pub fn new(id: usize) -> Self {
        Self(id)
    }
}

impl From<usize> for NodeId {
    fn from(id: usize) -> Self {
        Self(id)
    }
}

/// A node in the build graph
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Node {
    /// A build target defined in a BUILD file
    Target(TargetNode),
    /// An action (command) to execute
    Action(ActionNode),
    /// A file (source or generated)
    File(FileNode),
}

impl Node {
    /// Create a target node
    pub fn target(label: Label) -> Self {
        Self::Target(TargetNode::new(label))
    }

    /// Create an action node
    pub fn action(action_id: ActionId, command: Vec<String>) -> Self {
        Self::Action(ActionNode::new(action_id, command))
    }

    /// Create a source file node
    pub fn source_file(path: PathBuf) -> Self {
        Self::File(FileNode::source(path))
    }

    /// Create a generated file node
    pub fn generated_file(path: PathBuf, produced_by: ActionId) -> Self {
        Self::File(FileNode::generated(path, produced_by))
    }

    /// Get the label if this is a target node
    pub fn as_target(&self) -> Option<&TargetNode> {
        match self {
            Self::Target(t) => Some(t),
            _ => None,
        }
    }

    /// Get the action if this is an action node
    pub fn as_action(&self) -> Option<&ActionNode> {
        match self {
            Self::Action(a) => Some(a),
            _ => None,
        }
    }

    /// Get the file if this is a file node
    pub fn as_file(&self) -> Option<&FileNode> {
        match self {
            Self::File(f) => Some(f),
            _ => None,
        }
    }

    /// Check if this is a target node
    pub fn is_target(&self) -> bool {
        matches!(self, Self::Target(_))
    }

    /// Check if this is an action node
    pub fn is_action(&self) -> bool {
        matches!(self, Self::Action(_))
    }

    /// Check if this is a file node
    pub fn is_file(&self) -> bool {
        matches!(self, Self::File(_))
    }

    /// Get a display name for the node
    pub fn display_name(&self) -> String {
        match self {
            Self::Target(t) => t.label.to_string(),
            Self::Action(a) => format!("action:{}", a.action_id),
            Self::File(f) => f.path.to_string_lossy().into_owned(),
        }
    }
}

/// A target node representing a buildable unit
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TargetNode {
    /// The target's label
    pub label: Label,
    /// Rule type (e.g., "rust_binary", "genrule")
    pub rule_type: Option<String>,
}

impl TargetNode {
    pub fn new(label: Label) -> Self {
        Self {
            label,
            rule_type: None,
        }
    }

    pub fn with_rule_type(label: Label, rule_type: String) -> Self {
        Self {
            label,
            rule_type: Some(rule_type),
        }
    }
}

/// An action node representing a command to execute
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ActionNode {
    /// Unique action identifier
    pub action_id: ActionId,
    /// The command to execute
    pub command: Vec<String>,
    /// Description for display
    pub description: Option<String>,
}

impl ActionNode {
    pub fn new(action_id: ActionId, command: Vec<String>) -> Self {
        Self {
            action_id,
            command,
            description: None,
        }
    }

    pub fn with_description(action_id: ActionId, command: Vec<String>, description: String) -> Self {
        Self {
            action_id,
            command,
            description: Some(description),
        }
    }

    /// Get a short description of the action
    pub fn short_description(&self) -> String {
        if let Some(desc) = &self.description {
            desc.clone()
        } else if let Some(cmd) = self.command.first() {
            cmd.clone()
        } else {
            format!("action:{}", self.action_id)
        }
    }
}

/// The kind of file node
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FileKind {
    /// A source file that exists in the workspace
    Source,
    /// A file generated by an action
    Generated,
}

/// A file node representing a source or generated file
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct FileNode {
    /// Path to the file
    pub path: PathBuf,
    /// Whether this is a source or generated file
    pub kind: FileKind,
    /// If generated, the action that produces it
    pub produced_by: Option<ActionId>,
}

impl FileNode {
    /// Create a source file node
    pub fn source(path: PathBuf) -> Self {
        Self {
            path,
            kind: FileKind::Source,
            produced_by: None,
        }
    }

    /// Create a generated file node
    pub fn generated(path: PathBuf, produced_by: ActionId) -> Self {
        Self {
            path,
            kind: FileKind::Generated,
            produced_by: Some(produced_by),
        }
    }

    /// Check if this is a source file
    pub fn is_source(&self) -> bool {
        self.kind == FileKind::Source
    }

    /// Check if this is a generated file
    pub fn is_generated(&self) -> bool {
        self.kind == FileKind::Generated
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_label() -> Label {
        Label::parse("//pkg:target").unwrap()
    }

    #[test]
    fn create_target_node() {
        let label = test_label();
        let node = Node::target(label.clone());

        assert!(node.is_target());
        assert!(!node.is_action());
        assert!(!node.is_file());

        let target = node.as_target().unwrap();
        assert_eq!(target.label, label);
        assert!(target.rule_type.is_none());
    }

    #[test]
    fn create_target_with_rule_type() {
        let label = test_label();
        let target = TargetNode::with_rule_type(label.clone(), "rust_binary".to_string());

        assert_eq!(target.label, label);
        assert_eq!(target.rule_type, Some("rust_binary".to_string()));
    }

    #[test]
    fn create_action_node() {
        let action_id: ActionId = 42;
        let command = vec!["rustc".to_string(), "-o".to_string(), "out".to_string()];
        let node = Node::action(action_id, command.clone());

        assert!(node.is_action());
        assert!(!node.is_target());
        assert!(!node.is_file());

        let action = node.as_action().unwrap();
        assert_eq!(action.action_id, action_id);
        assert_eq!(action.command, command);
    }

    #[test]
    fn action_short_description() {
        let action_id: ActionId = 1;
        
        // With explicit description
        let action = ActionNode::with_description(
            action_id,
            vec!["rustc".to_string()],
            "Compiling main.rs".to_string(),
        );
        assert_eq!(action.short_description(), "Compiling main.rs");

        // Without description, uses command
        let action = ActionNode::new(action_id, vec!["rustc".to_string()]);
        assert_eq!(action.short_description(), "rustc");

        // Empty command
        let action = ActionNode::new(action_id, vec![]);
        assert_eq!(action.short_description(), "action:1");
    }

    #[test]
    fn create_source_file_node() {
        let path = PathBuf::from("src/main.rs");
        let node = Node::source_file(path.clone());

        assert!(node.is_file());
        assert!(!node.is_target());
        assert!(!node.is_action());

        let file = node.as_file().unwrap();
        assert_eq!(file.path, path);
        assert!(file.is_source());
        assert!(!file.is_generated());
        assert!(file.produced_by.is_none());
    }

    #[test]
    fn create_generated_file_node() {
        let path = PathBuf::from("out/binary");
        let action_id: ActionId = 99;
        let node = Node::generated_file(path.clone(), action_id);

        let file = node.as_file().unwrap();
        assert_eq!(file.path, path);
        assert!(!file.is_source());
        assert!(file.is_generated());
        assert_eq!(file.produced_by, Some(action_id));
    }

    #[test]
    fn node_display_name() {
        let target = Node::target(test_label());
        assert_eq!(target.display_name(), "//pkg:target");

        let action = Node::action(42, vec!["echo".to_string()]);
        assert_eq!(action.display_name(), "action:42");

        let file = Node::source_file(PathBuf::from("src/lib.rs"));
        assert_eq!(file.display_name(), "src/lib.rs");
    }

    #[test]
    fn node_id_from_usize() {
        let id: NodeId = 42.into();
        assert_eq!(id.0, 42);
        assert_eq!(id, NodeId::new(42));
    }
}
